### ISSUE TITLE
Unexpected Token => When Setting Up Server Parent

### ISSUE THREAD

**Issue by GiovanniL19** [raido/ember-window-messenger#1]
Hi!

When setting up the server parent ember throws me an unexpected token pointing to the following:
```
server.on('demo-data' (resolve, reject, query) => {
```

The entire code in the route is as follows:
```
import Ember from 'ember';

export default Ember.Route.extend({
	server: Ember.inject.service('window-messenger-server'),
	init() {
    this._super.apply(...arguments);

    server.on('demo-data' (resolve, reject, query) => {
      resolve('Some data');
    });
  }
});

```

I have followed the example code [here](https://github.com/raido/ember-window-messenger).
Sorry if I missing something, still trying to learn how all this works, thank you in advance :)

**Comment by raido** [comment]
Thank you, yes there appears to be a typo, it should be:

```
server.on('demo-data', (resolve, reject, query) => {
      resolve('Some data');
    });
```

**Comment by GiovanniL19** [comment]
Thank you @raido
