### ISSUE TITLE
Cannot send message from iFrame to Parent Window

### ISSUE THREAD

**Issue by GiovanniL19** [raido/ember-window-messenger#2]
Hi,

I am attempting to use this addon to pass messages from the iFrame to the Parent Window (not Parent to iFrame as implied in the examples). When attempting to do this, the client property is always an empty ember object. I can see this by printing ```console.log(controller.get('client'));``` and the object is always null.

```
  client: Ember.inject.service('window-messenger-client'),
  model: function(){
    console.log(this.get('client'));
    //return this.get('client').fetch('demo-data');
  },
```

Further troubleshooting lead to me to the resolve method however I don't think the code is ever being executed. 

```
server: Ember.inject.service('window-messenger-server'),

  init: function(){
    var server = this.get('server');
    console.log('sending...');
    server.on('demo-data', (resolve, reject, query) => {
      resolve('Some data');
      console.log('Sent');
    });
  },
```

the console log sent never appears. I have in my parent config/environment the following:

```
'ember-window-messenger': {
   //Parent is iFrame
   'parent': 'http://localhost:4200',
   //Target is Application
   'target-1': 'http://localhost:9999'
}
```

Do you know what I am doing wrong or could show me an example of communication from iFrame to Parent? 

p.s. What does this line mean ```this._super.apply(...arguments);```

Thank you in advance

**Comment by raido** [comment]
I have added a section to readme about communicating with frames and popup windows.
