### ISSUE TITLE
Method _isTargetParent returns window.opener instead of boolean when one is specified

### ISSUE THREAD

**Issue by agrinko** [raido/ember-window-messenger#7]
I noticed this issue when was trying to open a part of my application in a new tab (using link with target="_blank"). Basically this code means that whenever `window.opener` is specified, it is returned by this method (`_isTargetParent`) instead of boolean value, and thus always considered `true` in boolean context. So even when I specify messenger's target, it doesn't matter for `_targetFor` method which always returns actual window when it's opened in a new tab.

The issue happens in this line of `client.js`:

```javascript
let isEmbedded = win.self !== win.top || win.opener;
```

My guess was that you meant to wrap this condition into parenthesis: `win.self !== (win.top || win.opener)`, instead of original chunk without parenthesis, which is treated as `(win.self !== win.top) || win.opener`. Please correct me if I'm wrong.

Created a corresponding PR #6

**Comment by raido** [comment]
Thanks, your PR is merged.
